import React,{useMemo,useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import{MapPin,Search,Plus,Printer,Home,Save,ClipboardList,MapPinned,X}from'lucide-react';
import'./styles.css';
const uid=()=>crypto.randomUUID();
const seedScouts=[
{id:uid(),set:'Super Mutant Lodge',name:'Big Bear Performing Arts Center',address:'39707 Big Bear Blvd',city:'Big Bear Lake',state:'CA',zip:'92315',area:'Big Bear',contact:'',phone:'',email:'',scout:'',date:'',status:'Researching',notes:''},
{id:uid(),set:'Super Mutant Lodge',name:'Big Bear Convention Center',address:'42900 Big Bear Blvd',city:'Big Bear Lake',state:'CA',zip:'92315',area:'Big Bear',contact:'',phone:'',email:'',scout:'',date:'',status:'Researching',notes:''},
{id:uid(),set:'Super Mutant Lodge',name:'San Moritz Lodge',address:'24640 San Moritz Dr',city:'Crestline',state:'CA',zip:'92325',area:'Lake Gregory',contact:'Ben Beitzel',phone:'818-856-0886',email:'ben@mtlocations.com',scout:'Rich Streeter',date:'',status:'Scouted',notes:''},
{id:uid(),set:'Super Mutant Lodge',name:'Tamarack Lodge Resort',address:'163 Twin Lakes Rd',city:'Mammoth Lakes',state:'CA',zip:'93546',area:'Mammoth',contact:'',phone:'',email:'',scout:'Taylor Erickson',date:'',status:'Submitted',notes:''}
];
const seedFinal=[
{id:uid(),episode:'401',location:'Occidental College',address:'1600 Campus Road',city:'Los Angeles, CA 90041',contacts:'Peg Meehan, Unreel Locations\nT: (323) 953-6189\nE: unreellocations@aol.com',sets:'Int. Clay County Community College Classroom',scenes:'401.37A',key:'Taylor Erickson',dates:'Prep: Monday, July 8\nShoot/Wrap: Tuesday, July 9\nWrap: Wednesday, July 10',support:[{use:'BASECAMP, BREAKFAST CATERING, CREW & BG PARKING',place:'ROSE BOWL - Lot K\n738 West Dr, Pasadena, CA 91105',contact:'Joe Michalek\nC: (626) 524-4751\nE: jmichalek@rosebowlstadium.com'}]},
{id:uid(),episode:'401',location:'Kent Residence',address:'3751 Cloud Avenue',city:'Glendale, CA 91214',contacts:'Kent Clark, Owner\nC: (818) 689-0691\nE: kent.l.clark@gmail.com',sets:"Int. Bradley's House - Living Room\nInt. Bradley's House - Dining Room\nInt. Bradley's House - Bedroom",scenes:'401.39, 401.54, 401.53, 401.49',key:'Tiffany Le',dates:'Prep: Friday, July 5; Monday, July 8\nShoot: Tuesday, July 9; Wednesday, July 10\nWrap: Thursday, July 11; Friday, July 12',support:[]}
];
const statuses=['Needed','Researching','Contacted','Scout Scheduled','Scouted','Submitted','Director Approved','On Hold','Rejected','Selected'];
function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function App(){const[tab,setTab]=useState('tracker');const[scouts,setScouts]=useState(()=>load('ts-location-scouts',seedScouts));const[finals,setFinals]=useState(()=>load('ts-location-finals',seedFinal));const[q,setQ]=useState('');const[filters,setFilters]=useState({set:'',city:'',scout:'',status:'',date:''});const[editing,setEditing]=useState(null);
useEffect(()=>localStorage.setItem('ts-location-scouts',JSON.stringify(scouts)),[scouts]);useEffect(()=>localStorage.setItem('ts-location-finals',JSON.stringify(finals)),[finals]);
const filtered=useMemo(()=>scouts.filter(r=>{const hay=Object.values(r).join(' ').toLowerCase();return hay.includes(q.toLowerCase())&&(!filters.set||r.set===filters.set)&&(!filters.city||r.city===filters.city)&&(!filters.scout||r.scout===filters.scout)&&(!filters.status||r.status===filters.status)&&(!filters.date||r.date===filters.date)}),[scouts,q,filters]);
const update=(id,key,val)=>setScouts(v=>v.map(r=>r.id===id?{...r,[key]:val}:r));const promote=r=>{setFinals(v=>v.some(x=>x.sourceScoutId===r.id)?v:[...v,{id:uid(),sourceScoutId:r.id,episode:'',location:r.name,address:r.address,city:[r.city,r.state,r.zip].filter(Boolean).join(', '),contacts:[r.contact,r.phone,r.email].filter(Boolean).join('\n'),sets:r.set,scenes:'',key:r.scout,dates:'',support:[]}])};const changeStatus=(r,val)=>{update(r.id,'status',val);if(val==='Selected')promote({...r,status:val})};
return <div className="app"><header><button className="brand" onClick={()=>location.href=import.meta.env.VITE_HUB_URL||'https://taylorscout.com'}><span><MapPin/></span><b>TAYLOR SCOUT<small>PRODUCTION TOOLS · LOCATION LIST</small></b></button><div className="show-mark" aria-label="El Dorado"><img src="/el_dorado_logo.png" alt="El Dorado"/></div><button className="icon home-button" onClick={()=>location.href=import.meta.env.VITE_HUB_URL||'https://taylorscout.com'}><Home/></button></header><main><div className="title"><div><p>LOCATIONS DEPARTMENT</p><h1>Location List</h1><span>Scout candidates, approvals, and the final production location record.</span></div><div className="actions"><button onClick={()=>window.print()}><Printer/> Print</button><button className="primary" onClick={()=>setEditing({id:uid(),set:'',name:'',address:'',city:'',state:'CA',zip:'',area:'',contact:'',phone:'',email:'',scout:'',date:'',status:'Needed',notes:''})}><Plus/> Add Location</button></div></div><nav><button className={tab==='tracker'?'active':''} onClick={()=>setTab('tracker')}><ClipboardList/> Scout Tracker</button><button className={tab==='final'?'active':''} onClick={()=>setTab('final')}><MapPinned/> Final Locations</button></nav>
{tab==='tracker'?<><section className="filters"><label className="search"><Search/><input placeholder="Search name, address, set, city, scout, notes…" value={q} onChange={e=>setQ(e.target.value)}/></label>{['set','city','scout','status'].map(k=><select key={k} value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">All {k}s</option>{[...new Set(scouts.map(r=>r[k]).filter(Boolean))].sort().map(x=><option>{x}</option>)}</select>)}<input type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/></section><div className="table-wrap"><table><thead><tr><th>Set</th><th>Name / Address</th><th>Property Contact</th><th>Area</th><th>Scouted By</th><th>Scout Date</th><th>Status</th><th>Notes</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><input value={r.set} onChange={e=>update(r.id,'set',e.target.value)}/></td><td><button className="name" onClick={()=>setEditing(r)}>{r.name||'Untitled'}</button><small>{r.address}<br/>{r.city}, {r.state} {r.zip}</small></td><td><input value={r.contact} placeholder="Contact" onChange={e=>update(r.id,'contact',e.target.value)}/><small>{r.phone}{r.email&&<><br/>{r.email}</>}</small></td><td><input value={r.area} onChange={e=>update(r.id,'area',e.target.value)}/></td><td><input value={r.scout} onChange={e=>update(r.id,'scout',e.target.value)}/></td><td><input type="date" value={r.date} onChange={e=>update(r.id,'date',e.target.value)}/></td><td><select className={'status s-'+r.status.replaceAll(' ','-').toLowerCase()} value={r.status} onChange={e=>changeStatus(r,e.target.value)}>{statuses.map(s=><option>{s}</option>)}</select></td><td><textarea value={r.notes} onChange={e=>update(r.id,'notes',e.target.value)}/></td></tr>)}</tbody></table></div></>:<FinalList rows={finals} setRows={setFinals} q={q} setQ={setQ}/>}</main>{editing&&<Editor row={editing} onClose={()=>setEditing(null)} onSave={r=>{setScouts(v=>v.some(x=>x.id===r.id)?v.map(x=>x.id===r.id?r:x):[r,...v]);setEditing(null)}}/>}</div>}
function Editor({row,onClose,onSave}){const[r,setR]=useState({...row});return <div className="modal-bg"><div className="modal"><button className="close" onClick={onClose}><X/></button><p>SCOUT RECORD</p><h2>{r.name||'New Location'}</h2><div className="form">{['set','name','address','city','state','zip','area','contact','phone','email','scout','date'].map(k=><label>{k.replace(/([A-Z])/g,' $1')}<input type={k==='date'?'date':'text'} value={r[k]||''} onChange={e=>setR({...r,[k]:e.target.value})}/></label>)}<label>Status<select value={r.status} onChange={e=>setR({...r,status:e.target.value})}>{statuses.map(s=><option>{s}</option>)}</select></label><label className="full">Notes<textarea value={r.notes||''} onChange={e=>setR({...r,notes:e.target.value})}/></label></div><button className="primary save" onClick={()=>onSave(r)}><Save/> Save Location</button></div></div>}
function FinalList({rows,setRows,q,setQ}){return <section className="final"><div className="final-tools"><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search location, address, set, scene, key…"/></label><button className="primary" onClick={()=>setRows(v=>[...v,{id:uid(),episode:'',location:'New Location',address:'',city:'',contacts:'',sets:'',scenes:'',key:'',dates:'',support:[]}])}><Plus/> Add Final Location</button></div><div className="print-title">EL DORADO — FINAL LOCATION LIST</div>{rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())).map(r=><article className="location-block" key={r.id}><div className="bar"><span>LOCATION INFORMATION</span><span>EPISODE / SCENE NAMES / NUMBERS</span><span>LOCATION DEPT CONTACT & DATE(S)</span></div><div className="cols"><div><h3 contentEditable suppressContentEditableWarning onBlur={e=>editFinal(setRows,r.id,'location',e.currentTarget.innerText)}>{r.location}</h3><p contentEditable suppressContentEditableWarning onBlur={e=>editFinal(setRows,r.id,'address',e.currentTarget.innerText)}>{r.address}</p><p contentEditable suppressContentEditableWarning onBlur={e=>editFinal(setRows,r.id,'city',e.currentTarget.innerText)}>{r.city}</p><pre contentEditable suppressContentEditableWarning onBlur={e=>editFinal(setRows,r.id,'contacts',e.currentTarget.innerText)}>{r.contacts}</pre></div><div><p><b>{r.sets}</b></p><p>Scenes: {r.scenes}</p></div><div><p><b>{r.key}</b></p><pre>{r.dates}</pre></div></div>{r.support.map((s,i)=><div className="support" key={i}><div>{s.use}</div><div>{s.place}</div><div>{s.contact}</div></div>)}</article>)}</section>}
function editFinal(setRows,id,key,val){setRows(v=>v.map(r=>r.id===id?{...r,[key]:val}:r))}
createRoot(document.getElementById('root')).render(<App/>);
