import { createSharedCookieStorage } from './sharedAuthStorage';
import { createClient } from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const configured=Boolean(url&&key);
export const supabase=configured?createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:createSharedCookieStorage()}}):null;
export const getShowId=()=>new URLSearchParams(location.search).get('show')||new URLSearchParams(location.search).get('showId')||'';
export async function session(){if(!configured)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data.session}

const permissionCache=new Map();
async function fallbackAccess(showId){const{data,error}=await supabase.rpc('show_access_role',{p_show_id:showId});if(error)throw error;return data==='owner'||data==='editor'?'write':data==='viewer'?'read':'none'}
export async function getLocationListAccess(showId,{refresh=false}={}){if(!configured||!showId)return'none';if(!refresh&&permissionCache.has(showId))return permissionCache.get(showId);let level='none';const{data,error}=await supabase.rpc('tool_access_level',{p_show_id:showId,p_tool:'locations'});if(error&&error.code!=='42883')throw error;level=error?await fallbackAccess(showId):(data||'none');permissionCache.set(showId,level);return level}
async function requireRead(showId){const level=await getLocationListAccess(showId);if(!['read','write'].includes(level))throw new Error('You do not have access to Location List for this show.');return level}
async function requireWrite(showId){const level=await getLocationListAccess(showId);if(level!=='write')throw new Error('Location List is read-only for your account.');return level}
export async function getMyShowPermissions(showId){const{data,error}=await supabase.rpc('get_my_show_permissions',{p_show_id:showId});if(error&&error.code!=='42883')throw error;if(!error)return data;const level=await fallbackAccess(showId);return{tools:{locations:level},location_ids:null,episode_ids:null,lifecycle:false}}

export async function loadLocations(showId,{includeArchived=false}={}){await requireRead(showId);const{data,error}=await supabase.from('production_locations').select('*').eq('show_id',showId).order('created_at');if(error)throw error;return(data||[]).filter(r=>includeArchived||!r.metadata?.archived_at)}
async function lifecycleState(showId,locationId){if(!locationId)return{current:null,deleted:false};const[{data:current,error:loadError},{data:tombstone,error:tombError}]=await Promise.all([supabase.from('production_locations').select('metadata').eq('show_id',showId).eq('id',locationId).maybeSingle(),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).eq('tool_key',`location-tombstone:${locationId}`).maybeSingle()]);if(loadError)throw loadError;if(tombError)throw tombError;return{current,deleted:Boolean(tombstone)}}
export async function upsertLocation(row){await requireWrite(row.showId);const state=await lifecycleState(row.showId,row.id);if(state.deleted||state.current?.metadata?.archived_at)return{skipped:true,reason:state.deleted?'deleted':'archived',id:row.id};const payload={id:row.id,show_id:row.showId,episode_id:row.episodeId||null,episode_name:row.episodeName||null,set_name:row.set||'',location_name:row.name||'Untitled Location',address:row.address||'',city:row.city||'',state:row.state||'',postal_code:row.zip||'',area:row.area||'',contact_name:row.contact||'',contact_phone:row.phone||'',contact_email:row.email||'',scout_name:row.scout||'',scout_date:row.date||null,status:row.status||'Needed',notes:row.notes||'',is_final:Boolean(row.isFinal),source:'location_list',metadata:{...(state.current?.metadata||{}),final:row.final??state.current?.metadata?.final??null,canonical_location_id:row.id||state.current?.metadata?.canonical_location_id||null}};const{data,error}=await supabase.from('production_locations').upsert(payload).select().single();if(error)throw error;return data}
export async function archiveLocation(showId,locationId,reason='Archived'){await requireWrite(showId);const{data,error}=await supabase.rpc('archive_production_location',{p_show_id:showId,p_location_id:locationId,p_reason:reason});if(error){if(error.code==='42883')throw new Error('Location lifecycle migration has not been installed yet.');throw error}return data}
export async function restoreLocation(showId,locationId){await requireWrite(showId);const{data,error}=await supabase.rpc('restore_production_location',{p_show_id:showId,p_location_id:locationId});if(error){if(error.code==='42883')throw new Error('Location lifecycle migration has not been installed yet.');throw error}return data}
export async function permanentDeleteLocation(showId,locationId,{reason='Permanent delete',confirmationLocationId}={}){await requireWrite(showId);if(confirmationLocationId!==locationId)throw new Error('Permanent delete requires the exact canonical Location ID confirmation');const{data,error}=await supabase.rpc('permanent_delete_production_location',{p_show_id:showId,p_location_id:locationId,p_confirmation_location_id:confirmationLocationId,p_reason:reason});if(error){if(error.code==='42883')throw new Error('Location lifecycle migration has not been installed yet.');throw error}return data}
export function subscribeLocations(showId,callback){if(!configured||!showId)return()=>{};const ch=supabase.channel(`locations:${showId}`).on('postgres_changes',{event:'*',schema:'public',table:'production_locations',filter:`show_id=eq.${showId}`},callback).on('postgres_changes',{event:'*',schema:'public',table:'tool_documents',filter:`show_id=eq.${showId}`},p=>{const k=p.new?.tool_key||p.old?.tool_key||'';if(k.startsWith('budget-location:')||k.startsWith('bible-location:')||k.startsWith('location-tombstone:'))callback(p)}).subscribe();return()=>supabase.removeChannel(ch)}
