import { createSharedCookieStorage } from './sharedAuthStorage';
import { createClient } from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const configured=Boolean(url&&key);
export const supabase=configured?createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:createSharedCookieStorage()}}):null;
export const getShowId=()=>new URLSearchParams(location.search).get('show')||new URLSearchParams(location.search).get('showId')||'';
export async function session(){if(!configured)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data.session}
export async function loadShowOptions(showId){if(!configured||!showId)return{episodes:[],scouts:[]};const{data:show,error:showError}=await supabase.from('shows').select('show_data,payload,owner_id').eq('id',showId).single();if(showError)throw showError;const episodes=show?.show_data?.episodes||show?.payload?.episodes||[];const{data:members,error:memberError}=await supabase.from('show_members').select('user_id').eq('show_id',showId);if(memberError)throw memberError;const ids=[...new Set([show?.owner_id,...(members||[]).map(x=>x.user_id)].filter(Boolean))];let profiles=[];if(ids.length){const{data,error}=await supabase.from('profiles').select('id,display_name,email').in('id',ids);if(error)throw error;profiles=data||[]}const scouts=profiles.map(p=>({id:p.id,name:(p.display_name||p.email?.split('@')[0]||'User').trim(),email:p.email||''})).sort((a,b)=>a.name.localeCompare(b.name));return{episodes,scouts}}
const tombstoneKey=id=>`location-tombstone:${id}`;
export async function loadLocations(showId,{includeArchived=false}={}){const{data,error}=await supabase.from('production_locations').select('*').eq('show_id',showId).order('created_at');if(error)throw error;return(data||[]).filter(r=>includeArchived||!r.metadata?.archived_at)}
async function lifecycleState(showId,locationId){if(!locationId)return{current:null,deleted:false};const[{data:current,error:loadError},{data:tombstone,error:tombError}]=await Promise.all([supabase.from('production_locations').select('metadata').eq('show_id',showId).eq('id',locationId).maybeSingle(),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).eq('tool_key',tombstoneKey(locationId)).maybeSingle()]);if(loadError)throw loadError;if(tombError)throw tombError;return{current,deleted:Boolean(tombstone)}}
export async function upsertLocation(row){const state=await lifecycleState(row.showId,row.id);if(state.deleted||state.current?.metadata?.archived_at)return{skipped:true,reason:state.deleted?'deleted':'archived',id:row.id};const episodes=[...new Set([...(row.episodes||[]),row.episodeName,row.episodeId].filter(Boolean))];const sets=[...new Set([...(row.sets||[]),row.set].filter(Boolean))];const payload={id:row.id,show_id:row.showId,episode_id:row.episodeId||episodes[0]||null,episode_name:row.episodeName||episodes[0]||null,set_name:row.set||sets[0]||'',location_name:row.name||'Untitled Location',address:row.address||'',city:row.city||'',state:row.state||'',postal_code:row.zip||'',area:row.area||'',contact_name:row.contact||'',contact_phone:row.phone||'',contact_email:row.email||'',scout_name:row.scout||'',scout_date:row.date||null,status:row.status||'Needed',notes:row.notes||'',is_final:Boolean(row.isFinal),source:'location_list',metadata:{...(state.current?.metadata||{}),episodes,sets,place_id:row.placeId||state.current?.metadata?.place_id||null,latitude:row.latitude??state.current?.metadata?.latitude??null,longitude:row.longitude??state.current?.metadata?.longitude??null,final:row.final??state.current?.metadata?.final??null,canonical_location_id:row.id||state.current?.metadata?.canonical_location_id||null}};const{data,error}=await supabase.from('production_locations').upsert(payload).select().single();if(error)throw error;return data}
export async function archiveLocation(showId,locationId,reason='Archived'){const{data:row,error:loadError}=await supabase.from('production_locations').select('metadata,status').eq('show_id',showId).eq('id',locationId).single();if(loadError)throw loadError;const{data,error}=await supabase.from('production_locations').update({status:'Archived',metadata:{...(row.metadata||{}),archived_at:new Date().toISOString(),archive_reason:reason,archived_from_status:row.status||null}}).eq('show_id',showId).eq('id',locationId).select().single();if(error)throw error;return data}
export async function restoreLocation(showId,locationId){const{data:row,error:loadError}=await supabase.from('production_locations').select('metadata,status').eq('show_id',showId).eq('id',locationId).single();if(loadError)throw loadError;const metadata={...(row.metadata||{})};delete metadata.archived_at;delete metadata.archive_reason;const status=metadata.archived_from_status||'Needed';delete metadata.archived_from_status;const{data,error}=await supabase.from('production_locations').update({status,metadata}).eq('show_id',showId).eq('id',locationId).select().single();if(error)throw error;return data}
export async function permanentDeleteLocation(showId,locationId,{reason='Permanent delete',confirmationLocationId}={}){if(confirmationLocationId!==locationId)throw new Error('Permanent delete requires the exact canonical Location ID confirmation');const keys=[`budget-location:${locationId}`,`bible-location:${locationId}`];const[{data:linked,error:linkedError},{data:locationRecord,error:locationError}]=await Promise.all([supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).in('tool_key',keys),supabase.from('production_locations').select('*').eq('show_id',showId).eq('id',locationId).maybeSingle()]);if(linkedError)throw linkedError;if(locationError)throw locationError;const tombstone={version:2,locationId,deletedAt:new Date().toISOString(),reason,locationSnapshot:locationRecord||null,linkedRecords:(linked||[]).map(x=>({toolKey:x.tool_key,payload:x.payload,updatedAt:x.updated_at}))};const{error:tombError}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:tombstoneKey(locationId),payload:tombstone},{onConflict:'show_id,tool_key'});if(tombError)throw tombError;if(linked?.length){const{error}=await supabase.from('tool_documents').delete().eq('show_id',showId).in('tool_key',linked.map(x=>x.tool_key));if(error)throw error}const{error}=await supabase.from('production_locations').delete().eq('show_id',showId).eq('id',locationId);if(error)throw error;return tombstone}
export function subscribeLocations(showId,callback){if(!configured||!showId)return()=>{};const ch=supabase.channel(`locations:${showId}`).on('postgres_changes',{event:'*',schema:'public',table:'production_locations',filter:`show_id=eq.${showId}`},callback).on('postgres_changes',{event:'*',schema:'public',table:'tool_documents',filter:`show_id=eq.${showId}`},p=>{const k=p.new?.tool_key||p.old?.tool_key||'';if(k.startsWith('budget-location:')||k.startsWith('bible-location:')||k.startsWith('location-tombstone:'))callback(p)}).subscribe();return()=>supabase.removeChannel(ch)}
